# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: hero-columns
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  afbeelding:
    image: ""
    alt: ""
  col_1:
    icon: ""
    text: ""
  col_2:
    icon: ""
    text: ""
  col_3:
    icon: ""
    text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  afbeelding:
    image: https://picsum.photos/1200/800?random=1
    alt: Omschrijving van mijn afbeelding
  col_1:
    icon: flag
    text: Lorem ipsum
  col_2:
    icon: flag
    text: Lorem ipsum
  col_3:
    icon: flag
    text: Lorem ipsum

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
