[component]
structures = []
label = "hero-columns"
description = ""
icon = ""
tags = []

[props]
[props.afbeelding]
image = "https://picsum.photos/1200/800?random=1"
omschrijving = "Omschrijving van mijn afbeelding"

[props.col_1]
icon = "flag"
text = "Lorem ipsum"

[props.col_2]
icon = "flag"
text = "Lorem ipsum"

[props.col_3]
icon = "flag"
text = "Lorem ipsum"