[component]
structures = []
label = "nav"
description = ""
icon = ""
tags = []

[props]
_live_render = false
[[props.list]]
name = "Home"
url = "/"
[props.list.dropdown]
collection = "sloepen"
[[props.list.dropdown.custom]]
title = "Arrangementen"
url = "/aanbod/omgeving"