# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: nav
  description: ''
  icon: ''
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _live_render: false
  list:
    - name: ''
      url: ''
      dropdown:
        collection: ''
        custom:
          - title: ''
            url: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  list:
    - name: Home
      url: /
      dropdown:
        collection: sloepen
        custom:
          - title: Arrangementen
            url: /omgeving

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
