[component]
structures = []
label = "card-image"
description = ""
icon = ""
tags = []

[props]
title = "Mijn titel"

[props.afbeelding]
image = "https://picsum.photos/1200/800?random=1"
alt = "omschrijving van mijn afbeelding"

[props.button]
text = "+ meer info"
url = "#"