# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: card-small
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  btn_text: ""
  btn_url: ""
  afbeelding:
    image: ""
    alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Mijn titel
  btn_text: + meer info
  btn_url: "#"
  afbeelding:
    image: https://picsum.photos/1200/800?random=1
    alt: omschrijving van mijn afbeelding

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
