[component]
structures = []
label = "accordion"
description = ""
icon = ""
tags = []

[props]
[[props.list]]
[props.list.data]
title = "Question 1"
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, deleniti."