# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: map
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  url: https://www.google.com/maps/d/embed?mid=1-Gr8CUtQnISVsPaFX1spJl6q9tp5gW8y&usp=sharing

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
