[component]
structures = []
label = "carousel-vertical"
description = ""
icon = ""
tags = []

[props]
[[props.list]]
title = "lerem ipsum"
description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, deleniti."
