# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: carousel-vertical
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  list:
    - title: ""
      description: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  list:
    - title: lerem ipsum
      description: Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad, deleniti.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
