# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: gallery
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  gallery:
    - image: ""
      alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  gallery:
    - image: https://picsum.photos/1200/800?random=1
      alt: Beschrijving van mijn afbeelding

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
