[component]
structures = []
label = "card-checklist"
description = ""
icon = ""
tags = []

[props]
title = "Mijn titel"
description = "Mijn omschrijving"

checklist = ["Lorem Ipsum"]

[props.button]
text = "Button"
url = "#"