# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: card-checklist
  description: ''
  icon: ''
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: ''
  description: ''
  checklist:
    - Lorem Ipsum
  btn_text: ''
  btn_url: ''

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Mijn titel
  description: Mijn omschrijving
  checklist:
    - Lorem Ipsum
  btn_text: Button
  btn_url: '#'

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
