[component]
structures = []
label = "card-info"
description = ""
icon = ""
tags = []

[props]
_live_render = false
title = "Mijn titel"
description = "Mijn omschrijving"

[[props.list]]
label = "Label"
value = "Value"

[props.button]
text = "Button"
url = "#"
