# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: banner
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  _editor_link: true
  title: ""
  afbeelding:
    image: ""
    alt: ""
  button:
    text: ""
    url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: Mijn titel
  afbeelding:
    image: https://picsum.photos/1200/800?random=1
    alt: Omschrijving van mijn afbeelding
  button:
    text: Button
    url: "#"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
