[component]
structures = []
label = "banner"
description = ""
icon = ""
tags = []

[props]
_editor_link = true
title = "Mijn titel"


[props.afbeelding]
image = "https://picsum.photos/1200/800?random=1"
omschrijving = "Omschrijving van mijn afbeelding"

[props.button]
text = "Button"
url = "#"