[component]
structures = []
label = "hero-base"
description = ""
icon = ""
tags = []

[props]
title = "Mijn subtitel"
text = "Lorem ipsum"

[props.afbeelding]
image = "https://picsum.photos/1200/800?random=1"
omschrijving = "Omschrijving van mijn afbeelding"
