# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: huren-progress
  description: ""
  icon: ""
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  steps:
    - label: ""
      step: 1
      url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  steps:
    - label: label
      url: "#"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
