[component]
structures = []
label = "card-base"
description = ""
icon = ""
tags = []
_live_render = false

[props]
title = "Mijn titel"
description = "Mijn omschrijving"
url = "#"

[props.afbeelding]
image = "https://picsum.photos/1200/800?random=1"
alt = "Omschrijving van mijn afbeelding"
